spring:
  application:
    name: quartz

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://node-101:3306/demo
    username: gexingw
    password: 12345678

  quartz:
    auto-startup: true
    startup-delay: 1
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
#      org.quartz.scheduler.instanceName: Java-Example
      org.quartz.scheduler.instanceId: AUTO

      org.quartz.jobStore.isClustered: true
      org.quartz.threadPool.threadCount: 2

